FROM eclipse-temurin:11

ADD build/install/slowbackend-boot /app

WORKDIR /app

HEALTHCHECK --interval=15s --timeout=30s --start-period=30s --retries=3 CMD curl -f http://localhost:8080/actuator/health || exit 1

CMD ["/app/bin/slowbackend"]
